### PR TITLE
Add @banoonoo2 materials capturing + documenting data from June dump

### LINKED ISSUE #24: Add all of Anna's work to the repo

### PR DESCRIPTION
**Pull request by alexsoble**
Does this look correct @banoonoo2? Am I missing anything here?

Goal is to resolve #24.

### CODE REVIEW

**Comment by banoonoo2** [comment]
Yeah, this looks good. The final CSV files and documentation are going in the repo, and the external archive links are in the wiki.

Is there a good home on GitHub for the zip with all the PDFs? (It's 456 MB.) That would allow someone to download them all for offline work or alternative OCR.

**Comment by alexsoble** [comment]
Hmmm... I would say probably not this repo... Maybe an Amazon S3 instance?
Any ideas or recommendations @rajivsinclair?

**Comment by rajivsinclair** [comment]
not sure what the ideal spot it. it’s a shame that DocumentCloud doesn’t have an easier bulk download function. If you transfer the static file to me then I can definitely find you a permanent static spot for it in the cloud as a stop-gap solution. But the ideal spot would be something like archive.org ... will they not allow you to upload a giant zip file?

**Comment by alexsoble** [comment]
Cool. Merging this PR in now, we can discuss the location for the zip file on Slack or break it out into a separate issue.

**Pull request merged**
