### PR TITLE
Complete 6/3/16 Complaint and Document Indices

### PR DESCRIPTION
**Pull request by banoonoo2**
Here are the complete, ready-to-analyze Complaint and (PDF) Document indices for the June 3 portal.ipra.org doc drop. These were CSVs, but I can only upload them as XLSX. Please add them to the folder of ready-to-analyze files.

[2016-06-03-complaint-index.xlsx](https://github.com/invinst/shootings-data/files/303687/2016-06-03-complaint-index.xlsx)
[2016-06-03-document-index.xlsx](https://github.com/invinst/shootings-data/files/303688/2016-06-03-document-index.xlsx)

### CODE REVIEW

**Comment by alexsoble** [comment]
Wow @banoonoo2! Question: Where did the indices come from? Did you make these spreadsheets by hand?

**Comment by jayqi** [comment]
I noticed that the IPRA portal shows 102 entries now. I think one record was added sometime today. One of the other people at Chi Hack Night noticed there were two new SoundCloud audio tracks added 4 hours ago.

**Comment by rajivsinclair** [comment]
@alexsoble will you merge this PR once it’s ready?

**Comment by alexsoble** [comment]
@rajivsinclair I don't think @banoonoo2 is asking me to merge, just add those two files she posted into the repo. The commits on this PR don't really have anything to do with those files. 

@banoonoo2 I would love to chat sometime via Slack or Google Hangout if you have a minute this week or next! I want to thank you for all the work you're doing, talk about workflow, and answer any questions you have.

**Comment by alexsoble** [comment]
@jayqi HMMMMMM. Maybe some auto-scraping of the IPRA portal to look for changes would be a good idea?!?!

**Comment by banoonoo2** [comment]
@alexsoble Yes, hand-crafted artisanal spreadsheets by me! Yes, I'm available anytime today, anytime tomorrow, and Friday afternoon to chat.

@jayqi Yes, comparing the complaint index above to the IPRA portal, I see they added complaint 1080018, which happened 4/7/16 and was reported to IPRA 4/8/16, and that complaint has 2 SoundCloud audio files and 9 PDF documents. Here are updated indices:
[2016-06-03-complaint-index.xlsx](https://github.com/invinst/shootings-data/files/305809/2016-06-03-complaint-index.xlsx)
[2016-06-03-document-index.xlsx](https://github.com/invinst/shootings-data/files/305810/2016-06-03-document-index.xlsx)

I'm working on getting (1) all the audio and the handful of downloadable video files uploaded to Archive.org, (2) finishing indices for those, and (3) zipping everything up and offering it as a bulk download via WeTransfer, Dropbox, or maybe Google Drive.

Auto-scraping would be great! In the "scraping" issue thread, @freddymartinez9 said he's working on an IPRA scraper: https://github.com/freddymartinez9

**Comment by alexsoble** [comment]
@banoonoo2: great, let's schedule on Slack! Just sent you a DM.

@freddymartinez9: Excellent!

**Pull request closed without merging**
